package com.imbavchenko.bimil.presentation.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.remember

data class Strings(
    // App
    val appName: String,

    // Common
    val back: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val search: String,
    val clear: String,
    val yes: String,
    val no: String,
    val unknown: String,
    val all: String,
    val enabled: String,
    val disabled: String,
    val items: String,

    // Home Screen
    val settings: String,
    val addAccount: String,
    val searchServices: String,
    val favorites: String,
    val deleteAccount: String,
    val deleteAccountConfirm: String,
    val welcome: String,
    val addNewBimil: String,
    val welcomeMessage: String,
    val noResultsFound: String,
    val tryDifferentSearch: String,

    // Add/Edit Account Screen
    val editAccount: String,
    val basicInformation: String,
    val serviceName: String,
    val serviceNamePlaceholder: String,
    val usernameEmail: String,
    val usernameEmailPlaceholder: String,
    val websiteUrl: String,
    val websiteUrlPlaceholder: String,
    val category: String,
    val selectCategory: String,
    val loginType: String,
    val password: String,
    val sso: String,
    val ssoProvider: String,
    val provider: String,
    val other: String,
    val customProviderName: String,
    val passwordRequirements: String,
    val minimumLength: String,
    val specialCharacters: String,
    val uppercaseLetters: String,
    val lowercaseLetters: String,
    val numbers: String,
    val personalHint: String,
    val personalHintPlaceholder: String,
    val memo: String,
    val memoPlaceholder: String,

    // Settings Screen
    val security: String,
    val pinLock: String,
    val pinLockSubtitle: String,
    val changePinSubtitle: String,
    val biometricUnlock: String,
    val biometricSubtitle: String,
    val autoLock: String,
    val never: String,
    val immediately: String,
    val seconds30: String,
    val minute1: String,
    val minutes5: String,
    val general: String,
    val theme: String,
    val light: String,
    val dark: String,
    val system: String,
    val language: String,
    val region: String,
    val data: String,
    val savedItems: String,
    val createBackup: String,
    val createBackupSubtitle: String,
    val restoreBackup: String,
    val restoreBackupSubtitle: String,
    val deleteAllData: String,
    val deleteAllDataSubtitle: String,
    val about: String,
    val version: String,
    val privacyPolicy: String,
    val openSourceLicenses: String,

    // Account Card
    val via: String,
    val note: String,
    val removeFromFavorites: String,
    val addToFavorites: String,
    val digitPlus: String,

    // PIN / Lock Screen
    val enterPin: String,
    val setPin: String,
    val confirmPin: String,
    val changePin: String,
    val removePin: String,
    val pinMismatch: String,
    val pinTooShort: String,
    val wrongPin: String,
    val unlockBimil: String,
    val useBiometric: String,
    val biometricPromptTitle: String,
    val biometricPromptSubtitle: String,
    val biometricNotAvailable: String,
    val pinRequired: String,
    val pinSetSuccess: String,
    val pinRemoved: String,

    // Backup/Restore
    val enterBackupPassword: String,
    val confirmPassword: String,
    val passwordMismatch: String,
    val deleteAllDataConfirm: String,
    val confirm: String,
    val backupSuccess: String,
    val restoreSuccess: String
)

val EnglishStrings = Strings(
    // App
    appName = "Bimil",

    // Common
    back = "Back",
    save = "Save",
    cancel = "Cancel",
    delete = "Delete",
    search = "Search",
    clear = "Clear",
    yes = "Yes",
    no = "No",
    unknown = "?",
    all = "All",
    enabled = "Enabled",
    disabled = "Disabled",
    items = "items",

    // Home Screen
    settings = "Settings",
    addAccount = "Add Account",
    searchServices = "Search services...",
    favorites = "Favorites",
    deleteAccount = "Delete Account",
    deleteAccountConfirm = "Are you sure you want to delete '%s'?",
    welcome = "Welcome",
    addNewBimil = "Add a New Bimil",
    welcomeMessage = "Tap the + button\nto add a new\npassword information",
    noResultsFound = "No results found",
    tryDifferentSearch = "Try a different search term",

    // Add/Edit Account Screen
    editAccount = "Edit Account",
    basicInformation = "Basic Information",
    serviceName = "Service Name *",
    serviceNamePlaceholder = "e.g., Google, Netflix",
    usernameEmail = "Username / Email *",
    usernameEmailPlaceholder = "e.g., user@email.com",
    websiteUrl = "Website URL (optional)",
    websiteUrlPlaceholder = "e.g., https://example.com",
    category = "Category",
    selectCategory = "Select category",
    loginType = "Login Type",
    password = "Password",
    sso = "SSO",
    ssoProvider = "SSO Provider",
    provider = "Provider",
    other = "Other...",
    customProviderName = "Custom Provider Name",
    passwordRequirements = "Password Requirements",
    minimumLength = "Minimum Length",
    specialCharacters = "Special characters (!@#)",
    uppercaseLetters = "Uppercase letters (A-Z)",
    lowercaseLetters = "Lowercase letters (a-z)",
    numbers = "Numbers (0-9)",
    personalHint = "Personal Hint",
    personalHintPlaceholder = "e.g., birthday + first car name",
    memo = "Memo (optional)",
    memoPlaceholder = "Add any additional notes...",

    // Settings Screen
    security = "Security",
    pinLock = "PIN Lock",
    pinLockSubtitle = "Lock app with a PIN code",
    changePinSubtitle = "Modify your current PIN",
    biometricUnlock = "Biometric Unlock",
    biometricSubtitle = "Use fingerprint or face",
    autoLock = "Auto-lock",
    never = "Never",
    immediately = "Immediately",
    seconds30 = "30 seconds",
    minute1 = "1 minute",
    minutes5 = "5 minutes",
    general = "General",
    theme = "Theme",
    light = "Light",
    dark = "Dark",
    system = "System",
    language = "Language",
    region = "Region",
    data = "Data",
    savedItems = "Saved Items",
    createBackup = "Create Backup",
    createBackupSubtitle = "Export encrypted backup file",
    restoreBackup = "Restore Backup",
    restoreBackupSubtitle = "Import from backup file",
    deleteAllData = "Delete All Data",
    deleteAllDataSubtitle = "This cannot be undone",
    about = "About",
    version = "Version",
    privacyPolicy = "Privacy Policy",
    openSourceLicenses = "Open Source Licenses",

    // Account Card
    via = "via",
    note = "Note",
    removeFromFavorites = "Remove from favorites",
    addToFavorites = "Add to favorites",
    digitPlus = "digit+",

    // PIN / Lock Screen
    enterPin = "Enter PIN",
    setPin = "Set PIN",
    confirmPin = "Confirm PIN",
    changePin = "Change PIN",
    removePin = "Remove PIN",
    pinMismatch = "PINs do not match",
    pinTooShort = "PIN must be at least 4 digits",
    wrongPin = "Incorrect PIN",
    unlockBimil = "Unlock Bimil",
    useBiometric = "Use biometric",
    biometricPromptTitle = "Biometric Authentication",
    biometricPromptSubtitle = "Verify your identity",
    biometricNotAvailable = "Biometric not available",
    pinRequired = "PIN is required to enable biometric",
    pinSetSuccess = "PIN set successfully",
    pinRemoved = "PIN removed",

    // Backup/Restore
    enterBackupPassword = "Enter a password to encrypt your backup",
    confirmPassword = "Confirm Password",
    passwordMismatch = "Passwords do not match",
    deleteAllDataConfirm = "Are you sure you want to delete all data? This action cannot be undone.",
    confirm = "Confirm",
    backupSuccess = "Backup created successfully",
    restoreSuccess = "Data restored successfully"
)

val KoreanStrings = Strings(
    // App
    appName = "Bimil",

    // Common
    back = "뒤로",
    save = "저장",
    cancel = "취소",
    delete = "삭제",
    search = "검색",
    clear = "지우기",
    yes = "예",
    no = "아니오",
    unknown = "?",
    all = "전체",
    enabled = "사용",
    disabled = "사용 안함",
    items = "개",

    // Home Screen
    settings = "설정",
    addAccount = "계정 추가",
    searchServices = "서비스 검색...",
    favorites = "즐겨찾기",
    deleteAccount = "계정 삭제",
    deleteAccountConfirm = "'%s'을(를) 삭제하시겠습니까?",
    welcome = "환영합니다",
    addNewBimil = "새 비밀 추가",
    welcomeMessage = "+ 버튼을 눌러\n새 비밀번호 정보를\n추가하세요",
    noResultsFound = "검색 결과 없음",
    tryDifferentSearch = "다른 검색어를 입력해보세요",

    // Add/Edit Account Screen
    editAccount = "계정 수정",
    basicInformation = "기본 정보",
    serviceName = "서비스명 *",
    serviceNamePlaceholder = "예: Google, Netflix",
    usernameEmail = "사용자명 / 이메일 *",
    usernameEmailPlaceholder = "예: user@email.com",
    websiteUrl = "웹사이트 URL (선택)",
    websiteUrlPlaceholder = "예: https://example.com",
    category = "카테고리",
    selectCategory = "카테고리 선택",
    loginType = "로그인 유형",
    password = "비밀번호",
    sso = "SSO",
    ssoProvider = "SSO 제공자",
    provider = "제공자",
    other = "기타...",
    customProviderName = "사용자 정의 제공자",
    passwordRequirements = "비밀번호 요구사항",
    minimumLength = "최소 길이",
    specialCharacters = "특수문자 (!@#)",
    uppercaseLetters = "대문자 (A-Z)",
    lowercaseLetters = "소문자 (a-z)",
    numbers = "숫자 (0-9)",
    personalHint = "개인 힌트",
    personalHintPlaceholder = "예: 생일 + 첫 차 이름",
    memo = "메모 (선택)",
    memoPlaceholder = "추가 메모를 입력하세요...",

    // Settings Screen
    security = "보안",
    pinLock = "PIN 잠금",
    pinLockSubtitle = "PIN 코드로 앱 잠금",
    changePinSubtitle = "현재 PIN 변경",
    biometricUnlock = "생체인식 잠금해제",
    biometricSubtitle = "지문 또는 얼굴 사용",
    autoLock = "자동 잠금",
    never = "사용 안함",
    immediately = "즉시",
    seconds30 = "30초",
    minute1 = "1분",
    minutes5 = "5분",
    general = "일반",
    theme = "테마",
    light = "라이트",
    dark = "다크",
    system = "시스템",
    language = "언어",
    region = "지역",
    data = "데이터",
    savedItems = "저장된 항목",
    createBackup = "백업 생성",
    createBackupSubtitle = "암호화된 백업 파일 내보내기",
    restoreBackup = "백업 복원",
    restoreBackupSubtitle = "백업 파일에서 가져오기",
    deleteAllData = "모든 데이터 삭제",
    deleteAllDataSubtitle = "이 작업은 되돌릴 수 없습니다",
    about = "정보",
    version = "버전",
    privacyPolicy = "개인정보 처리방침",
    openSourceLicenses = "오픈소스 라이선스",

    // Account Card
    via = "via",
    note = "메모",
    removeFromFavorites = "즐겨찾기에서 제거",
    addToFavorites = "즐겨찾기에 추가",
    digitPlus = "자리+",

    // PIN / Lock Screen
    enterPin = "PIN 입력",
    setPin = "PIN 설정",
    confirmPin = "PIN 확인",
    changePin = "PIN 변경",
    removePin = "PIN 제거",
    pinMismatch = "PIN이 일치하지 않습니다",
    pinTooShort = "PIN은 최소 4자리여야 합니다",
    wrongPin = "잘못된 PIN",
    unlockBimil = "Bimil 잠금해제",
    useBiometric = "생체인식 사용",
    biometricPromptTitle = "생체인식 인증",
    biometricPromptSubtitle = "본인 확인",
    biometricNotAvailable = "생체인식을 사용할 수 없습니다",
    pinRequired = "생체인식을 활성화하려면 PIN이 필요합니다",
    pinSetSuccess = "PIN이 설정되었습니다",
    pinRemoved = "PIN이 제거되었습니다",

    // Backup/Restore
    enterBackupPassword = "백업을 암호화할 비밀번호를 입력하세요",
    confirmPassword = "비밀번호 확인",
    passwordMismatch = "비밀번호가 일치하지 않습니다",
    deleteAllDataConfirm = "모든 데이터를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
    confirm = "확인",
    backupSuccess = "백업이 생성되었습니다",
    restoreSuccess = "데이터가 복원되었습니다"
)

val JapaneseStrings = Strings(
    // App
    appName = "Bimil",

    // Common
    back = "戻る",
    save = "保存",
    cancel = "キャンセル",
    delete = "削除",
    search = "検索",
    clear = "クリア",
    yes = "はい",
    no = "いいえ",
    unknown = "?",
    all = "すべて",
    enabled = "有効",
    disabled = "無効",
    items = "件",

    // Home Screen
    settings = "設定",
    addAccount = "アカウント追加",
    searchServices = "サービスを検索...",
    favorites = "お気に入り",
    deleteAccount = "アカウントを削除",
    deleteAccountConfirm = "'%s'を削除しますか？",
    welcome = "ようこそ",
    addNewBimil = "新しいBimilを追加",
    welcomeMessage = "+ボタンをタップして\n新しいパスワード情報を\n追加してください",
    noResultsFound = "結果が見つかりません",
    tryDifferentSearch = "別の検索語を試してください",

    // Add/Edit Account Screen
    editAccount = "アカウント編集",
    basicInformation = "基本情報",
    serviceName = "サービス名 *",
    serviceNamePlaceholder = "例: Google, Netflix",
    usernameEmail = "ユーザー名 / メール *",
    usernameEmailPlaceholder = "例: user@email.com",
    websiteUrl = "ウェブサイトURL (任意)",
    websiteUrlPlaceholder = "例: https://example.com",
    category = "カテゴリー",
    selectCategory = "カテゴリーを選択",
    loginType = "ログインタイプ",
    password = "パスワード",
    sso = "SSO",
    ssoProvider = "SSOプロバイダー",
    provider = "プロバイダー",
    other = "その他...",
    customProviderName = "カスタムプロバイダー名",
    passwordRequirements = "パスワード要件",
    minimumLength = "最小文字数",
    specialCharacters = "特殊文字 (!@#)",
    uppercaseLetters = "大文字 (A-Z)",
    lowercaseLetters = "小文字 (a-z)",
    numbers = "数字 (0-9)",
    personalHint = "個人ヒント",
    personalHintPlaceholder = "例: 誕生日 + 最初の車の名前",
    memo = "メモ (任意)",
    memoPlaceholder = "追加のメモを入力...",

    // Settings Screen
    security = "セキュリティ",
    pinLock = "PINロック",
    pinLockSubtitle = "PINコードでアプリをロック",
    changePinSubtitle = "現在のPINを変更",
    biometricUnlock = "生体認証ロック解除",
    biometricSubtitle = "指紋または顔を使用",
    autoLock = "自動ロック",
    never = "しない",
    immediately = "すぐに",
    seconds30 = "30秒",
    minute1 = "1分",
    minutes5 = "5分",
    general = "一般",
    theme = "テーマ",
    light = "ライト",
    dark = "ダーク",
    system = "システム",
    language = "言語",
    region = "地域",
    data = "データ",
    savedItems = "保存済みアイテム",
    createBackup = "バックアップ作成",
    createBackupSubtitle = "暗号化バックアップファイルをエクスポート",
    restoreBackup = "バックアップ復元",
    restoreBackupSubtitle = "バックアップファイルからインポート",
    deleteAllData = "すべてのデータを削除",
    deleteAllDataSubtitle = "この操作は取り消せません",
    about = "情報",
    version = "バージョン",
    privacyPolicy = "プライバシーポリシー",
    openSourceLicenses = "オープンソースライセンス",

    // Account Card
    via = "via",
    note = "メモ",
    removeFromFavorites = "お気に入りから削除",
    addToFavorites = "お気に入りに追加",
    digitPlus = "桁+",

    // PIN / Lock Screen
    enterPin = "PINを入力",
    setPin = "PINを設定",
    confirmPin = "PINを確認",
    changePin = "PINを変更",
    removePin = "PINを削除",
    pinMismatch = "PINが一致しません",
    pinTooShort = "PINは4桁以上必要です",
    wrongPin = "PINが間違っています",
    unlockBimil = "Bimilのロック解除",
    useBiometric = "生体認証を使用",
    biometricPromptTitle = "生体認証",
    biometricPromptSubtitle = "本人確認",
    biometricNotAvailable = "生体認証は利用できません",
    pinRequired = "生体認証を有効にするにはPINが必要です",
    pinSetSuccess = "PINが設定されました",
    pinRemoved = "PINが削除されました",

    // Backup/Restore
    enterBackupPassword = "バックアップを暗号化するパスワードを入力してください",
    confirmPassword = "パスワード確認",
    passwordMismatch = "パスワードが一致しません",
    deleteAllDataConfirm = "すべてのデータを削除してもよろしいですか？この操作は元に戻せません。",
    confirm = "確認",
    backupSuccess = "バックアップが作成されました",
    restoreSuccess = "データが復元されました"
)

val ChineseStrings = Strings(
    // App
    appName = "Bimil",

    // Common
    back = "返回",
    save = "保存",
    cancel = "取消",
    delete = "删除",
    search = "搜索",
    clear = "清除",
    yes = "是",
    no = "否",
    unknown = "?",
    all = "全部",
    enabled = "已启用",
    disabled = "已禁用",
    items = "项",

    // Home Screen
    settings = "设置",
    addAccount = "添加账户",
    searchServices = "搜索服务...",
    favorites = "收藏夹",
    deleteAccount = "删除账户",
    deleteAccountConfirm = "确定要删除'%s'吗？",
    welcome = "欢迎",
    addNewBimil = "添加新的Bimil",
    welcomeMessage = "点击+按钮\n添加新的\n密码信息",
    noResultsFound = "未找到结果",
    tryDifferentSearch = "请尝试其他搜索词",

    // Add/Edit Account Screen
    editAccount = "编辑账户",
    basicInformation = "基本信息",
    serviceName = "服务名称 *",
    serviceNamePlaceholder = "例如: Google, Netflix",
    usernameEmail = "用户名 / 邮箱 *",
    usernameEmailPlaceholder = "例如: user@email.com",
    websiteUrl = "网站URL (可选)",
    websiteUrlPlaceholder = "例如: https://example.com",
    category = "分类",
    selectCategory = "选择分类",
    loginType = "登录类型",
    password = "密码",
    sso = "SSO",
    ssoProvider = "SSO提供商",
    provider = "提供商",
    other = "其他...",
    customProviderName = "自定义提供商名称",
    passwordRequirements = "密码要求",
    minimumLength = "最小长度",
    specialCharacters = "特殊字符 (!@#)",
    uppercaseLetters = "大写字母 (A-Z)",
    lowercaseLetters = "小写字母 (a-z)",
    numbers = "数字 (0-9)",
    personalHint = "个人提示",
    personalHintPlaceholder = "例如: 生日 + 第一辆车的名字",
    memo = "备注 (可选)",
    memoPlaceholder = "添加其他备注...",

    // Settings Screen
    security = "安全",
    pinLock = "PIN锁",
    pinLockSubtitle = "使用PIN码锁定应用",
    changePinSubtitle = "修改当前PIN",
    biometricUnlock = "生物识别解锁",
    biometricSubtitle = "使用指纹或面容",
    autoLock = "自动锁定",
    never = "从不",
    immediately = "立即",
    seconds30 = "30秒",
    minute1 = "1分钟",
    minutes5 = "5分钟",
    general = "通用",
    theme = "主题",
    light = "浅色",
    dark = "深色",
    system = "跟随系统",
    language = "语言",
    region = "地区",
    data = "数据",
    savedItems = "已保存项目",
    createBackup = "创建备份",
    createBackupSubtitle = "导出加密备份文件",
    restoreBackup = "恢复备份",
    restoreBackupSubtitle = "从备份文件导入",
    deleteAllData = "删除所有数据",
    deleteAllDataSubtitle = "此操作无法撤销",
    about = "关于",
    version = "版本",
    privacyPolicy = "隐私政策",
    openSourceLicenses = "开源许可",

    // Account Card
    via = "通过",
    note = "备注",
    removeFromFavorites = "从收藏夹移除",
    addToFavorites = "添加到收藏夹",
    digitPlus = "位+",

    // PIN / Lock Screen
    enterPin = "输入PIN",
    setPin = "设置PIN",
    confirmPin = "确认PIN",
    changePin = "更改PIN",
    removePin = "移除PIN",
    pinMismatch = "PIN不匹配",
    pinTooShort = "PIN必须至少4位数",
    wrongPin = "PIN错误",
    unlockBimil = "解锁Bimil",
    useBiometric = "使用生物识别",
    biometricPromptTitle = "生物识别认证",
    biometricPromptSubtitle = "验证您的身份",
    biometricNotAvailable = "生物识别不可用",
    pinRequired = "启用生物识别需要先设置PIN",
    pinSetSuccess = "PIN设置成功",
    pinRemoved = "PIN已移除",

    // Backup/Restore
    enterBackupPassword = "输入密码以加密您的备份",
    confirmPassword = "确认密码",
    passwordMismatch = "密码不匹配",
    deleteAllDataConfirm = "您确定要删除所有数据吗？此操作无法撤销。",
    confirm = "确认",
    backupSuccess = "备份创建成功",
    restoreSuccess = "数据恢复成功"
)

val GermanStrings = Strings(
    // App
    appName = "Bimil",

    // Common
    back = "Zuruck",
    save = "Speichern",
    cancel = "Abbrechen",
    delete = "Loschen",
    search = "Suchen",
    clear = "Loschen",
    yes = "Ja",
    no = "Nein",
    unknown = "?",
    all = "Alle",
    enabled = "Aktiviert",
    disabled = "Deaktiviert",
    items = "Eintr.",

    // Home Screen
    settings = "Einstellungen",
    addAccount = "Konto hinzufugen",
    searchServices = "Dienste suchen...",
    favorites = "Favoriten",
    deleteAccount = "Konto loschen",
    deleteAccountConfirm = "Mochten Sie '%s' wirklich loschen?",
    welcome = "Willkommen",
    addNewBimil = "Neues Bimil hinzufugen",
    welcomeMessage = "Tippen Sie auf +\num neue\nPasswortinfos hinzuzufugen",
    noResultsFound = "Keine Ergebnisse gefunden",
    tryDifferentSearch = "Versuchen Sie einen anderen Suchbegriff",

    // Add/Edit Account Screen
    editAccount = "Konto bearbeiten",
    basicInformation = "Grundinformationen",
    serviceName = "Dienstname *",
    serviceNamePlaceholder = "z.B. Google, Netflix",
    usernameEmail = "Benutzername / E-Mail *",
    usernameEmailPlaceholder = "z.B. user@email.com",
    websiteUrl = "Website-URL (optional)",
    websiteUrlPlaceholder = "z.B. https://example.com",
    category = "Kategorie",
    selectCategory = "Kategorie wahlen",
    loginType = "Anmeldetyp",
    password = "Passwort",
    sso = "SSO",
    ssoProvider = "SSO-Anbieter",
    provider = "Anbieter",
    other = "Andere...",
    customProviderName = "Eigener Anbietername",
    passwordRequirements = "Passwortanforderungen",
    minimumLength = "Mindestlange",
    specialCharacters = "Sonderzeichen (!@#)",
    uppercaseLetters = "Grossbuchstaben (A-Z)",
    lowercaseLetters = "Kleinbuchstaben (a-z)",
    numbers = "Zahlen (0-9)",
    personalHint = "Personlicher Hinweis",
    personalHintPlaceholder = "z.B. Geburtstag + erstes Auto",
    memo = "Notiz (optional)",
    memoPlaceholder = "Zusatzliche Notizen hinzufugen...",

    // Settings Screen
    security = "Sicherheit",
    pinLock = "PIN-Sperre",
    pinLockSubtitle = "App mit PIN-Code sperren",
    changePinSubtitle = "Aktuelle PIN andern",
    biometricUnlock = "Biometrische Entsperrung",
    biometricSubtitle = "Fingerabdruck oder Gesicht verwenden",
    autoLock = "Automatische Sperre",
    never = "Nie",
    immediately = "Sofort",
    seconds30 = "30 Sekunden",
    minute1 = "1 Minute",
    minutes5 = "5 Minuten",
    general = "Allgemein",
    theme = "Design",
    light = "Hell",
    dark = "Dunkel",
    system = "System",
    language = "Sprache",
    region = "Region",
    data = "Daten",
    savedItems = "Gespeicherte Elemente",
    createBackup = "Backup erstellen",
    createBackupSubtitle = "Verschlusselte Backup-Datei exportieren",
    restoreBackup = "Backup wiederherstellen",
    restoreBackupSubtitle = "Aus Backup-Datei importieren",
    deleteAllData = "Alle Daten loschen",
    deleteAllDataSubtitle = "Dies kann nicht ruckgangig gemacht werden",
    about = "Info",
    version = "Version",
    privacyPolicy = "Datenschutzrichtlinie",
    openSourceLicenses = "Open-Source-Lizenzen",

    // Account Card
    via = "uber",
    note = "Notiz",
    removeFromFavorites = "Aus Favoriten entfernen",
    addToFavorites = "Zu Favoriten hinzufugen",
    digitPlus = "Stellen+",

    // PIN / Lock Screen
    enterPin = "PIN eingeben",
    setPin = "PIN festlegen",
    confirmPin = "PIN bestatigen",
    changePin = "PIN andern",
    removePin = "PIN entfernen",
    pinMismatch = "PINs stimmen nicht uberein",
    pinTooShort = "PIN muss mindestens 4 Ziffern haben",
    wrongPin = "Falsche PIN",
    unlockBimil = "Bimil entsperren",
    useBiometric = "Biometrie verwenden",
    biometricPromptTitle = "Biometrische Authentifizierung",
    biometricPromptSubtitle = "Identitat bestatigen",
    biometricNotAvailable = "Biometrie nicht verfugbar",
    pinRequired = "PIN erforderlich fur Biometrie",
    pinSetSuccess = "PIN erfolgreich festgelegt",
    pinRemoved = "PIN entfernt",

    // Backup/Restore
    enterBackupPassword = "Geben Sie ein Passwort ein, um Ihre Sicherung zu verschlusseln",
    confirmPassword = "Passwort bestatigen",
    passwordMismatch = "Passworter stimmen nicht uberein",
    deleteAllDataConfirm = "Sind Sie sicher, dass Sie alle Daten loschen mochten? Diese Aktion kann nicht ruckgangig gemacht werden.",
    confirm = "Bestatigen",
    backupSuccess = "Sicherung erfolgreich erstellt",
    restoreSuccess = "Daten erfolgreich wiederhergestellt"
)

fun getStrings(language: Language): Strings {
    return when (language) {
        Language.ENGLISH -> EnglishStrings
        Language.KOREAN -> KoreanStrings
        Language.JAPANESE -> JapaneseStrings
        Language.CHINESE -> ChineseStrings
        Language.GERMAN -> GermanStrings
    }
}

val LocalStrings = compositionLocalOf { EnglishStrings }

@Composable
fun ProvideStrings(
    language: Language,
    content: @Composable () -> Unit
) {
    val strings = remember(language) { getStrings(language) }
    CompositionLocalProvider(LocalStrings provides strings) {
        content()
    }
}

@Composable
fun strings(): Strings = LocalStrings.current
